import { Worker } from "bullmq";
import { HumanMessage } from "@langchain/core/messages";
import { connection } from "../config/redis.js";
import db from "../models/index.js";
import { compileWorkflow } from "../helpers/compiler.js";

const { WorkflowRun, Workflow } = db;

const worker = new Worker(
	"workflow-execution",
	async (job) => {
		const { workflowId, runId, metadata } = job.data;

		console.log(
			`👷 [Job ID: ${job.id}] Processing Run [${runId}] for Workflow: ${workflowId}`
		);

		await WorkflowRun.findByIdAndUpdate(runId, {
			status: "RUNNING",
			$push: {
				logs: {
					action:
						"Worker picked up job from Redis queue. Beginning execution execution.",
				},
			},
		});

		await Workflow.findByIdAndUpdate(workflowId, {
			$set: {
				"schedule.status": "RUNNING",
				"schedule.lastRunId": runId,
				"schedule.lastRunAt": new Date(),
			},
		});

		const startTime = Date.now();

		try {
			const executableGraph = await compileWorkflow(workflowId);

			const finalState = await executableGraph.invoke(
				{
					runId: runId,
				},
				{
					configurable: { thread_id: runId },
				}
			);

			const executionTimeMs = Date.now() - startTime;

			const finalMessages = finalState.messages;
			const lastMessage = finalMessages[finalMessages.length - 1];
			const finalOutput = lastMessage
				? lastMessage.content
				: "No terminal output generated by agents.";

			await WorkflowRun.findByIdAndUpdate(runId, {
				status: "COMPLETED",
				output: finalOutput,
				graphState: finalState,
				"metrics.executionTimeMs": executionTimeMs,
				$push: {
					logs: {
						action: `Workflow computation completed successfully in ${executionTimeMs}ms.`,
					},
				},
			});

			await Workflow.findByIdAndUpdate(workflowId, {
				$set: {
					"schedule.status": "COMPLETED",
					"schedule.enabled": false,
				},
			});

			// 6. Channel Router: Direct delivery to messaging channels
			// if (metadata && metadata.channel === "telegram" && metadata.chatId) {
			// 	console.log(
			// 		`📱 Routing pipeline results directly to Telegram Chat: ${metadata.chatId}`
			// 	);
			// 	await sendTelegramMessage(metadata.chatId, finalOutput);
			// }

			return finalOutput;
		} catch (error) {
			const executionTimeMs = Date.now() - startTime;
			console.error(
				`🚨 Background Worker Exception occurred on Job [${job.id}]:`,
				error.message
			);

			await WorkflowRun.findByIdAndUpdate(runId, {
				status: "FAILED",
				errorReason: error.message,
				"metrics.executionTimeMs": executionTimeMs,
				$push: {
					logs: {
						action: `Execution Core Crashed: ${error.message}`,
					},
				},
			});

			await Workflow.findByIdAndUpdate(workflowId, {
				$set: {
					"schedule.status": "FAILED",
				},
			});

			// if (metadata && metadata.channel === "telegram" && metadata.chatId) {
			// 	await sendTelegramMessage(
			// 		metadata.chatId,
			// 		`⚠️ Operational Error: Your workflow execution encountered a technical failure during processing.`
			// 	);
			// }

			throw error;
		}
	},
	{
		connection,
		concurrency: 2,
	}
);

worker.on("completed", (job) => {
	console.log(`✨ BullMQ: Job [${job.id}] pipeline cycle fully wrapped.`);
});

worker.on("failed", (job, err) => {
	console.error(
		`🚨 BullMQ: Job [${job?.id}] marked as exhausted or failed completely:`,
		err.message
	);
});

export default worker;
